### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by rohanku**
:robot: I have created a release *beep* *boop*
---

<details><summary>cache: 0.3.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))
</details>

<details><summary>codegen: 0.5.0</summary>

### Features

* **codegen:** derive macro for implementing FromSaved ([#243](https://github.com/substrate-labs/substrate2/issues/243)) ([48acae0](https://github.com/substrate-labs/substrate2/commit/48acae0fb8915c4f968223268c92077f2deda979))
* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * examples bumped from 0.1.0 to 0.2.0
  * dev-dependencies
    * substrate bumped from <=0.4.0 to <=0.5.0
    * sky130pdk bumped from <=0.4.0 to <=0.5.0
    * spectre bumped from <=0.4.0 to <=0.5.0
</details>

<details><summary>config: 0.2.2</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * cache bumped from 0.2.1 to 0.3.0
</details>

<details><summary>examples: 0.2.0</summary>

### Features

* **codegen:** derive macro for implementing FromSaved ([#243](https://github.com/substrate-labs/substrate2/issues/243)) ([48acae0](https://github.com/substrate-labs/substrate2/commit/48acae0fb8915c4f968223268c92077f2deda979))

### Dependencies

* The following workspace dependencies were updated
  * dev-dependencies
    * substrate bumped from <=0.4.0 to <=0.5.0
    * sky130pdk bumped from <=0.4.0 to <=0.5.0
    * spectre bumped from <=0.4.0 to <=0.5.0
</details>

<details><summary>pathtree: 0.2.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))
</details>

<details><summary>scir: 0.4.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))
</details>

<details><summary>sky130pdk: 0.5.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * substrate bumped from 0.4.0 to 0.5.0
    * spectre bumped from 0.4.0 to 0.5.0
</details>

<details><summary>spectre: 0.5.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * cache bumped from 0.2.1 to 0.3.0
    * scir bumped from 0.3.0 to 0.4.0
    * substrate bumped from 0.4.0 to 0.5.0
</details>

<details><summary>spice: 0.3.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * scir bumped from 0.3.0 to 0.4.0
</details>

<details><summary>substrate: 0.5.0</summary>

### Features

* **codegen:** derive macro for implementing FromSaved ([#243](https://github.com/substrate-labs/substrate2/issues/243)) ([48acae0](https://github.com/substrate-labs/substrate2/commit/48acae0fb8915c4f968223268c92077f2deda979))
* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * config bumped from 0.2.1 to 0.2.2
    * examples bumped from 0.1.0 to 0.2.0
    * cache bumped from 0.2.1 to 0.3.0
    * codegen bumped from 0.4.0 to 0.5.0
    * scir bumped from 0.3.0 to 0.4.0
    * pathtree bumped from 0.1.0 to 0.2.0
    * spice bumped from 0.2.0 to 0.3.0
    * type_dispatch bumped from 0.1.0 to 0.2.0
  * dev-dependencies
    * sky130pdk bumped from <=0.4.0 to <=0.5.0
    * spectre bumped from <=0.4.0 to <=0.5.0
</details>

<details><summary>tests: 0.0.0</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * substrate bumped from 0.4.0 to 0.5.0
    * scir bumped from 0.3.0 to 0.4.0
    * cache bumped from 0.2.1 to 0.3.0
    * spice bumped from 0.2.0 to 0.3.0
    * spectre bumped from 0.4.0 to 0.5.0
    * sky130pdk bumped from 0.4.0 to 0.5.0
</details>

<details><summary>type_dispatch: 0.2.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * type_dispatch_macros bumped from 0.1.0 to 0.2.0
</details>

<details><summary>type_dispatch_macros: 0.2.0</summary>

### Features

* **terminals:** add support for terminal paths ([#236](https://github.com/substrate-labs/substrate2/issues/236)) ([3fba7f6](https://github.com/substrate-labs/substrate2/commit/3fba7f6227bbf2efcaf79d849c79175e44d783a4))

### Dependencies

* The following workspace dependencies were updated
  * dev-dependencies
    * type_dispatch bumped from <=0.1.0 to <=0.2.0
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by rahulk29 — APPROVED** [review]

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/codegen-v0.5.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/config-v0.2.2 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/examples-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/cache-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/pathtree-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/scir-v0.4.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/spice-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/type_dispatch-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/type_dispatch_macros-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/sky130pdk-v0.5.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/substrate-v0.5.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/spectre-v0.5.0 :sunflower:

**Pull request merged**
