### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by rohanku**
:robot: I have created a release *beep* *boop*
---

<details><summary>cache: 0.2.0</summary>

### Features

* **cache-config:** allow configuration of cache via config files ([#192](https://github.com/substrate-labs/substrate2/issues/192)) ([0461402](https://github.com/substrate-labs/substrate2/commit/0461402edfc1ec0886bbb25cf5471ee8480754fc))
* **cache:** add local cache implementation ([#168](https://github.com/substrate-labs/substrate2/issues/168)) ([676b585](https://github.com/substrate-labs/substrate2/commit/676b5851488594824c4cd31c310e4b7d7bdb0a59))
* **cache:** implement persistent caching ([#171](https://github.com/substrate-labs/substrate2/issues/171)) ([1f8ea24](https://github.com/substrate-labs/substrate2/commit/1f8ea24f805085392bfd1a2067bb8774d0fa4ae4))
* **namespacing:** enforce namespace format ([#194](https://github.com/substrate-labs/substrate2/issues/194)) ([90b1ebd](https://github.com/substrate-labs/substrate2/commit/90b1ebdee52dc934cdde2996520e1acecf323c81))
* **remote-cache:** add initial implementation of remote-cache ([#166](https://github.com/substrate-labs/substrate2/issues/166)) ([7d90aab](https://github.com/substrate-labs/substrate2/commit/7d90aab47c282cf90e814ffce357a1e694c0c357))
* **testing:** clean up wording/naming and add new tests ([#190](https://github.com/substrate-labs/substrate2/issues/190)) ([d60076b](https://github.com/substrate-labs/substrate2/commit/d60076b49a7f03663cddb5abe59ec047dcab8462))
* **tests:** show server errors and fix port picking ([#195](https://github.com/substrate-labs/substrate2/issues/195)) ([2e477e3](https://github.com/substrate-labs/substrate2/commit/2e477e3a733e6668ea1222c8a6796798e7dca9dd))
* **windows:** fix issues for windows ([#197](https://github.com/substrate-labs/substrate2/issues/197)) ([008b607](https://github.com/substrate-labs/substrate2/commit/008b607b2c21c14ac3106dca6eb74d806131ef8f))

### Bug Fixes

* **tests:** increase cache server wait time ([#167](https://github.com/substrate-labs/substrate2/issues/167)) ([b0db3aa](https://github.com/substrate-labs/substrate2/commit/b0db3aa6285367de1650e972c9cf7e2185a68250))
* **tests:** use `portpicker` to pick available ports in tests ([#170](https://github.com/substrate-labs/substrate2/issues/170)) ([072998c](https://github.com/substrate-labs/substrate2/commit/072998c32a97988494d2312b2676479ed4cb28fe))
</details>

<details><summary>codegen: 0.3.0</summary>

### Features

* **codegen:** implement derive proc macro for layout hard macros ([#200](https://github.com/substrate-labs/substrate2/issues/200)) ([5138224](https://github.com/substrate-labs/substrate2/commit/5138224013f537e678dfb20204e964852ed40ccb))
* **gds-import:** implement GDS to RawCell importer ([#196](https://github.com/substrate-labs/substrate2/issues/196)) ([fc37eeb](https://github.com/substrate-labs/substrate2/commit/fc37eeb6bac10779491b98bcadcc0eeaeb7d8ec5))
* **proc-macros:** codegen for schematic hard macros ([#191](https://github.com/substrate-labs/substrate2/issues/191)) ([50240b1](https://github.com/substrate-labs/substrate2/commit/50240b167876873c4133315d35298b44e8eeac51))
* **proc-macros:** derive macros for geometry traits ([#164](https://github.com/substrate-labs/substrate2/issues/164)) ([a86074a](https://github.com/substrate-labs/substrate2/commit/a86074a69b714b1be551ae00c775beb04c13f776))
* **proc-macros:** support enums, tuple structs, etc. ([#165](https://github.com/substrate-labs/substrate2/issues/165)) ([bda83f7](https://github.com/substrate-labs/substrate2/commit/bda83f7c3049178024b114eb4e1bf65c6a128998))
* **proc-macros:** support generics in derive schematic/layout data ([#169](https://github.com/substrate-labs/substrate2/issues/169)) ([5bc11d8](https://github.com/substrate-labs/substrate2/commit/5bc11d8eee266c21247694299285b6147631166e))
* **simulation:** proc macros for implementing Supports on tuples ([#163](https://github.com/substrate-labs/substrate2/issues/163)) ([bf77832](https://github.com/substrate-labs/substrate2/commit/bf778329d6e9fd317bea789d093c4c7d8790f5ac))
* **tiling:** array and grid tiling API ([#201](https://github.com/substrate-labs/substrate2/issues/201)) ([b3b7c2b](https://github.com/substrate-labs/substrate2/commit/b3b7c2bfb7ba72198872d0f08ded3e0bc757479d))

### Bug Fixes

* **ci:** add workaround for dev deps ([180c924](https://github.com/substrate-labs/substrate2/commit/180c92434b38a5da8d5d1f0494faae6a0b227c26))
* **ci:** test another workaround for dev deps ([c15bc6d](https://github.com/substrate-labs/substrate2/commit/c15bc6d30afc02512237223db5f31cd9cb089ede))
* **tests:** increase cache server wait time ([#167](https://github.com/substrate-labs/substrate2/issues/167)) ([b0db3aa](https://github.com/substrate-labs/substrate2/commit/b0db3aa6285367de1650e972c9cf7e2185a68250))

### Dependencies

* The following workspace dependencies were updated
  * dev-dependencies
    * substrate bumped from <=0.2.0 to <=0.3.0
    * sky130pdk bumped from <=0.2.0 to <=0.3.0
</details>

<details><summary>config: 0.2.0</summary>

### Features

* **cache-config:** allow configuration of cache via config files ([#192](https://github.com/substrate-labs/substrate2/issues/192)) ([0461402](https://github.com/substrate-labs/substrate2/commit/0461402edfc1ec0886bbb25cf5471ee8480754fc))
* **tiling:** array and grid tiling API ([#201](https://github.com/substrate-labs/substrate2/issues/201)) ([b3b7c2b](https://github.com/substrate-labs/substrate2/commit/b3b7c2bfb7ba72198872d0f08ded3e0bc757479d))
* **windows:** fix issues for windows ([#197](https://github.com/substrate-labs/substrate2/issues/197)) ([008b607](https://github.com/substrate-labs/substrate2/commit/008b607b2c21c14ac3106dca6eb74d806131ef8f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * cache bumped from 0.1.0 to 0.2.0
</details>

<details><summary>gds: 0.2.0</summary>

### Features

* **gds-import:** implement GDS to RawCell importer ([#196](https://github.com/substrate-labs/substrate2/issues/196)) ([fc37eeb](https://github.com/substrate-labs/substrate2/commit/fc37eeb6bac10779491b98bcadcc0eeaeb7d8ec5))
</details>

<details><summary>geometry: 0.3.0</summary>

### Features

* **gds-import:** implement GDS to RawCell importer ([#196](https://github.com/substrate-labs/substrate2/issues/196)) ([fc37eeb](https://github.com/substrate-labs/substrate2/commit/fc37eeb6bac10779491b98bcadcc0eeaeb7d8ec5))
* **gds:** gds reexport test ([#199](https://github.com/substrate-labs/substrate2/issues/199)) ([93d3cd5](https://github.com/substrate-labs/substrate2/commit/93d3cd555c1cb4a76a8845f4401e98d327b5d674))
* **proc-macros:** derive macros for geometry traits ([#164](https://github.com/substrate-labs/substrate2/issues/164)) ([a86074a](https://github.com/substrate-labs/substrate2/commit/a86074a69b714b1be551ae00c775beb04c13f776))
* **tiling:** array and grid tiling API ([#201](https://github.com/substrate-labs/substrate2/issues/201)) ([b3b7c2b](https://github.com/substrate-labs/substrate2/commit/b3b7c2bfb7ba72198872d0f08ded3e0bc757479d))
</details>

<details><summary>scir: 0.2.0</summary>

### Features

* **cache:** implement persistent caching ([#171](https://github.com/substrate-labs/substrate2/issues/171)) ([1f8ea24](https://github.com/substrate-labs/substrate2/commit/1f8ea24f805085392bfd1a2067bb8774d0fa4ae4))
* **merging:** add API for merging two SCIR libraries ([#183](https://github.com/substrate-labs/substrate2/issues/183)) ([a0006aa](https://github.com/substrate-labs/substrate2/commit/a0006aa4dbe62c2dda66eea306987e56eaabe181))
* **proc-macros:** codegen for schematic hard macros ([#191](https://github.com/substrate-labs/substrate2/issues/191)) ([50240b1](https://github.com/substrate-labs/substrate2/commit/50240b167876873c4133315d35298b44e8eeac51))
* **scir-instances:** allow Substrate users to instantiate raw SCIR instances ([#184](https://github.com/substrate-labs/substrate2/issues/184)) ([8fd5192](https://github.com/substrate-labs/substrate2/commit/8fd5192fd2017ab04e9e3220612d0a132702bb2e))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * uniquify bumped from 0.1.0 to 0.2.0
</details>

<details><summary>sky130pdk: 0.3.0</summary>

### Features

* **gds-import:** implement GDS to RawCell importer ([#196](https://github.com/substrate-labs/substrate2/issues/196)) ([fc37eeb](https://github.com/substrate-labs/substrate2/commit/fc37eeb6bac10779491b98bcadcc0eeaeb7d8ec5))
* **pdks:** PDKs store the names of schematic primitives ([#185](https://github.com/substrate-labs/substrate2/issues/185)) ([3446ba8](https://github.com/substrate-labs/substrate2/commit/3446ba869f564f844b39ee524b52106954a293c5))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * substrate bumped from 0.2.0 to 0.3.0
    * spectre bumped from 0.2.0 to 0.3.0
</details>

<details><summary>spectre: 0.3.0</summary>

### Features

* **cache:** implement persistent caching ([#171](https://github.com/substrate-labs/substrate2/issues/171)) ([1f8ea24](https://github.com/substrate-labs/substrate2/commit/1f8ea24f805085392bfd1a2067bb8774d0fa4ae4))
* **codegen:** implement derive proc macro for layout hard macros ([#200](https://github.com/substrate-labs/substrate2/issues/200)) ([5138224](https://github.com/substrate-labs/substrate2/commit/5138224013f537e678dfb20204e964852ed40ccb))
* **executors:** executor API and local executor implementation ([#161](https://github.com/substrate-labs/substrate2/issues/161)) ([c372d51](https://github.com/substrate-labs/substrate2/commit/c372d511e1c67ad976dc86958c87e9ad13bdfde4))
* **windows:** fix issues for windows ([#197](https://github.com/substrate-labs/substrate2/issues/197)) ([008b607](https://github.com/substrate-labs/substrate2/commit/008b607b2c21c14ac3106dca6eb74d806131ef8f))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * scir bumped from 0.1.0 to 0.2.0
    * cache bumped from 0.1.0 to 0.2.0
    * substrate bumped from 0.2.0 to 0.3.0
</details>

<details><summary>spice: 0.1.0</summary>

### Features

* **conversion:** convert parsed SPICE to SCIR ([#178](https://github.com/substrate-labs/substrate2/issues/178)) ([9cb7bc3](https://github.com/substrate-labs/substrate2/commit/9cb7bc3ba549ae12e7a59465241c848800c39363))
* **organization:** move `spice` from netlist/ to libs/ ([#174](https://github.com/substrate-labs/substrate2/issues/174)) ([bd31a44](https://github.com/substrate-labs/substrate2/commit/bd31a4481aef357daeb2c217dd7f403f6f882f78))
* **proc-macros:** codegen for schematic hard macros ([#191](https://github.com/substrate-labs/substrate2/issues/191)) ([50240b1](https://github.com/substrate-labs/substrate2/commit/50240b167876873c4133315d35298b44e8eeac51))
* **scir-instances:** allow Substrate users to instantiate raw SCIR instances ([#184](https://github.com/substrate-labs/substrate2/issues/184)) ([8fd5192](https://github.com/substrate-labs/substrate2/commit/8fd5192fd2017ab04e9e3220612d0a132702bb2e))
* **spice-to-scir:** do not convert blackboxed subcircuits ([#179](https://github.com/substrate-labs/substrate2/issues/179)) ([c501313](https://github.com/substrate-labs/substrate2/commit/c501313334279b636f1d8b581357dd805177f1ca))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * scir bumped from 0.1.0 to 0.2.0
</details>

<details><summary>substrate: 0.3.0</summary>

### Features

* **cache-config:** allow configuration of cache via config files ([#192](https://github.com/substrate-labs/substrate2/issues/192)) ([0461402](https://github.com/substrate-labs/substrate2/commit/0461402edfc1ec0886bbb25cf5471ee8480754fc))
* **cache:** implement persistent caching ([#171](https://github.com/substrate-labs/substrate2/issues/171)) ([1f8ea24](https://github.com/substrate-labs/substrate2/commit/1f8ea24f805085392bfd1a2067bb8774d0fa4ae4))
* **codegen:** implement derive proc macro for layout hard macros ([#200](https://github.com/substrate-labs/substrate2/issues/200)) ([5138224](https://github.com/substrate-labs/substrate2/commit/5138224013f537e678dfb20204e964852ed40ccb))
* **executors:** executor API and local executor implementation ([#161](https://github.com/substrate-labs/substrate2/issues/161)) ([c372d51](https://github.com/substrate-labs/substrate2/commit/c372d511e1c67ad976dc86958c87e9ad13bdfde4))
* **executors:** LSF (bsub) executor implementation ([#162](https://github.com/substrate-labs/substrate2/issues/162)) ([ff8404a](https://github.com/substrate-labs/substrate2/commit/ff8404abf75e6d6a4c82109adde0bcac48b6f33f))
* **gds-import:** implement GDS to RawCell importer ([#196](https://github.com/substrate-labs/substrate2/issues/196)) ([fc37eeb](https://github.com/substrate-labs/substrate2/commit/fc37eeb6bac10779491b98bcadcc0eeaeb7d8ec5))
* **gds:** gds reexport test ([#199](https://github.com/substrate-labs/substrate2/issues/199)) ([93d3cd5](https://github.com/substrate-labs/substrate2/commit/93d3cd555c1cb4a76a8845f4401e98d327b5d674))
* **pdks:** PDKs store the names of schematic primitives ([#185](https://github.com/substrate-labs/substrate2/issues/185)) ([3446ba8](https://github.com/substrate-labs/substrate2/commit/3446ba869f564f844b39ee524b52106954a293c5))
* **proc-macros:** codegen for schematic hard macros ([#191](https://github.com/substrate-labs/substrate2/issues/191)) ([50240b1](https://github.com/substrate-labs/substrate2/commit/50240b167876873c4133315d35298b44e8eeac51))
* **remote-cache:** add initial implementation of remote-cache ([#166](https://github.com/substrate-labs/substrate2/issues/166)) ([7d90aab](https://github.com/substrate-labs/substrate2/commit/7d90aab47c282cf90e814ffce357a1e694c0c357))
* **scir-instances:** allow Substrate users to instantiate raw SCIR instances ([#184](https://github.com/substrate-labs/substrate2/issues/184)) ([8fd5192](https://github.com/substrate-labs/substrate2/commit/8fd5192fd2017ab04e9e3220612d0a132702bb2e))
* **simulation:** proc macros for implementing Supports on tuples ([#163](https://github.com/substrate-labs/substrate2/issues/163)) ([bf77832](https://github.com/substrate-labs/substrate2/commit/bf778329d6e9fd317bea789d093c4c7d8790f5ac))
* **tiling:** array and grid tiling API ([#201](https://github.com/substrate-labs/substrate2/issues/201)) ([b3b7c2b](https://github.com/substrate-labs/substrate2/commit/b3b7c2bfb7ba72198872d0f08ded3e0bc757479d))

### Bug Fixes

* **ci:** fix doc tests for substrate crate ([#158](https://github.com/substrate-labs/substrate2/issues/158)) ([d7e9437](https://github.com/substrate-labs/substrate2/commit/d7e943734b1eadfe64deabb7602f5bbf41cd8806))

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * config bumped from 0.1.0 to 0.2.0
    * cache bumped from 0.1.0 to 0.2.0
    * codegen bumped from 0.2.0 to 0.3.0
    * geometry bumped from 0.2.0 to 0.3.0
    * gds bumped from 0.1.0 to 0.2.0
    * scir bumped from 0.1.0 to 0.2.0
    * uniquify bumped from 0.1.0 to 0.2.0
    * spice bumped from 0.0.0 to 0.1.0
  * dev-dependencies
    * sky130pdk bumped from <=0.2.0 to <=0.3.0
</details>

<details><summary>tests: 0.0.0</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * geometry bumped from 0.2.0 to 0.3.0
    * substrate bumped from 0.2.0 to 0.3.0
    * scir bumped from 0.1.0 to 0.2.0
    * cache bumped from 0.1.0 to 0.2.0
    * spice bumped from 0.0.0 to 0.1.0
    * spectre bumped from 0.2.0 to 0.3.0
    * sky130pdk bumped from 0.2.0 to 0.3.0
</details>

<details><summary>uniquify: 0.2.0</summary>

### Features

* **merging:** add API for merging two SCIR libraries ([#183](https://github.com/substrate-labs/substrate2/issues/183)) ([a0006aa](https://github.com/substrate-labs/substrate2/commit/a0006aa4dbe62c2dda66eea306987e56eaabe181))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by rahulk29 — APPROVED** [review]

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/codegen-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/config-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/gds-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/cache-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/geometry-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/spice-v0.1.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/uniquify-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/sky130pdk-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/scir-v0.2.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/substrate-v0.3.0 :sunflower:

**Comment by rohanku** [comment]
:robot: Release is at https://github.com/substrate-labs/substrate2/releases/tag/spectre-v0.3.0 :sunflower:

**Pull request merged**
